### ISSUE TITLE
Please upgrade to Node 16

### ISSUE THREAD

**Issue by fhoeben** [franzbischoff/replace_envs#177]
When I use this action in my workflow I get the following warning.

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: franzbischoff/replace_envs@v1

Can you make a version using Node.js 16?

**Comment by MatthieuWinalist** [comment]
Would be great !

**Comment by fhoeben** [comment]
@franzbischoff  
Node 20 by now...

**Comment by franzbischoff** [comment]
asap

**Comment by fhoeben** [comment]
@franzbischoff  Thanks!

Should we use `franzbischoff/replace_envs@v2` now? Maybe you can update that in the README also?
